# Generated by Django 5.1.4 on 2025-01-08 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('title', models.CharField(max_length=255, verbose_name='Budget name')),
                ('related_user', models.UUIDField(verbose_name='Related user id')),
                ('related_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='budgets.currency', verbose_name='Related currency')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('operation_type', models.CharField(choices=[('ADD', 'Addition'), ('SUB', 'Subtraction')], default='ADD', max_length=3, verbose_name='Operation type')),
                ('amount', models.FloatField(verbose_name='Operation amount')),
                ('title', models.CharField(blank=True, max_length=124, verbose_name='Operation name')),
                ('related_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='budgets.budget', verbose_name='Related budget')),
                ('related_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='budgets.category', verbose_name='Related category')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
    ]
