# Generated by Django 5.1.4 on 2025-01-09 00:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_budget_amount_alter_currency_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=11, verbose_name='Budget amount'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='related_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='budgets.currency', verbose_name='Related currency'),
        ),
    ]
