# Generated by Django 5.1.4 on 2025-01-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budget_amount_alter_budget_related_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount',
            new_name='initial_amount',
        ),
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Operation amount'),
        ),
    ]
